/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteImport } from './routes/user'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AccountantRouteImport } from './routes/accountant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as InvoicesNewRouteImport } from './routes/invoices/new'
import { Route as InvoicesIdRouteImport } from './routes/invoices/$id'
import { Route as ContractorsUserIdRouteImport } from './routes/contractors/$userId'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminReportingRouteImport } from './routes/admin/reporting'
import { Route as AdminProcessedRouteImport } from './routes/admin/processed'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountantRoute = AccountantRouteImport.update({
  id: '/accountant',
  path: '/accountant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesNewRoute = InvoicesNewRouteImport.update({
  id: '/invoices/new',
  path: '/invoices/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIdRoute = InvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractorsUserIdRoute = ContractorsUserIdRouteImport.update({
  id: '/contractors/$userId',
  path: '/contractors/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportingRoute = AdminReportingRouteImport.update({
  id: '/admin/reporting',
  path: '/admin/reporting',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProcessedRoute = AdminProcessedRouteImport.update({
  id: '/admin/processed',
  path: '/admin/processed',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accountant': typeof AccountantRoute
  '/settings': typeof SettingsRoute
  '/user': typeof UserRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/processed': typeof AdminProcessedRoute
  '/admin/reporting': typeof AdminReportingRoute
  '/admin/users': typeof AdminUsersRoute
  '/contractors/$userId': typeof ContractorsUserIdRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accountant': typeof AccountantRoute
  '/settings': typeof SettingsRoute
  '/user': typeof UserRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/processed': typeof AdminProcessedRoute
  '/admin/reporting': typeof AdminReportingRoute
  '/admin/users': typeof AdminUsersRoute
  '/contractors/$userId': typeof ContractorsUserIdRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/admin': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accountant': typeof AccountantRoute
  '/settings': typeof SettingsRoute
  '/user': typeof UserRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/processed': typeof AdminProcessedRoute
  '/admin/reporting': typeof AdminReportingRoute
  '/admin/users': typeof AdminUsersRoute
  '/contractors/$userId': typeof ContractorsUserIdRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accountant'
    | '/settings'
    | '/user'
    | '/admin/categories'
    | '/admin/processed'
    | '/admin/reporting'
    | '/admin/users'
    | '/contractors/$userId'
    | '/invoices/$id'
    | '/invoices/new'
    | '/admin/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accountant'
    | '/settings'
    | '/user'
    | '/admin/categories'
    | '/admin/processed'
    | '/admin/reporting'
    | '/admin/users'
    | '/contractors/$userId'
    | '/invoices/$id'
    | '/invoices/new'
    | '/admin'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/accountant'
    | '/settings'
    | '/user'
    | '/admin/categories'
    | '/admin/processed'
    | '/admin/reporting'
    | '/admin/users'
    | '/contractors/$userId'
    | '/invoices/$id'
    | '/invoices/new'
    | '/admin/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountantRoute: typeof AccountantRoute
  SettingsRoute: typeof SettingsRoute
  UserRoute: typeof UserRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminProcessedRoute: typeof AdminProcessedRoute
  AdminReportingRoute: typeof AdminReportingRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ContractorsUserIdRoute: typeof ContractorsUserIdRoute
  InvoicesIdRoute: typeof InvoicesIdRoute
  InvoicesNewRoute: typeof InvoicesNewRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accountant': {
      id: '/accountant'
      path: '/accountant'
      fullPath: '/accountant'
      preLoaderRoute: typeof AccountantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/new': {
      id: '/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof InvoicesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/$id': {
      id: '/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof InvoicesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contractors/$userId': {
      id: '/contractors/$userId'
      path: '/contractors/$userId'
      fullPath: '/contractors/$userId'
      preLoaderRoute: typeof ContractorsUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reporting': {
      id: '/admin/reporting'
      path: '/admin/reporting'
      fullPath: '/admin/reporting'
      preLoaderRoute: typeof AdminReportingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/processed': {
      id: '/admin/processed'
      path: '/admin/processed'
      fullPath: '/admin/processed'
      preLoaderRoute: typeof AdminProcessedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountantRoute: AccountantRoute,
  SettingsRoute: SettingsRoute,
  UserRoute: UserRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminProcessedRoute: AdminProcessedRoute,
  AdminReportingRoute: AdminReportingRoute,
  AdminUsersRoute: AdminUsersRoute,
  ContractorsUserIdRoute: ContractorsUserIdRoute,
  InvoicesIdRoute: InvoicesIdRoute,
  InvoicesNewRoute: InvoicesNewRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
